# Generated by Django 6.0.2 on 2026-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Intended selling/rent price set during purchase', max_digits=12),
        ),
    ]
