# Generated by Django 6.0.2 on 2026-05-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_date',
            field=models.DateField(blank=True, help_text='Date items leave the inventory', null=True),
        ),
    ]
