# Generated by Django 6.0.2 on 2026-05-04 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_dispatch_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('staff_name', models.CharField(help_text='Person accompanying (Bnda)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatch_forms', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_forms', to='orders.order')),
            ],
            options={
                'verbose_name': 'Dispatch Form',
                'verbose_name_plural': 'Dispatch Forms',
                'db_table': 'dispatch_form',
                'ordering': ['-created_at'],
            },
        ),
    ]
