# Generated by Django 6.0.2 on 2026-05-06 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0008_dispatchform'),
        ('products', '0007_stockreservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchform',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer for standalone gate pass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_forms', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='dispatchform',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Type of vehicle (e.g. Truck, Bike)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchform',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_forms', to='orders.order'),
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Cached product name', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_extra', models.BooleanField(default=False, help_text='True if item was not part of the original order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.dispatchform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Dispatch Item',
                'verbose_name_plural': 'Dispatch Items',
                'db_table': 'dispatch_item',
                'ordering': ['created_at'],
            },
        ),
    ]
