# Generated by Django 6.0.2 on 2026-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_dispatchform_customer_dispatchform_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchform',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchform',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchform',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
