# Generated by Django 6.0.2 on 2026-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_dispatchform_dispatch_date_dispatchform_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchform',
            name='event_location',
            field=models.CharField(blank=True, help_text='Location of the event', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dispatchform',
            name='event_name',
            field=models.CharField(blank=True, help_text='Name of the event', max_length=255, null=True),
        ),
    ]
