# Generated by Django 6.0.2 on 2026-04-04 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_quotation_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(default=datetime.date(2026, 4, 19)),
        ),
    ]
