# Generated by Django 6.0.2 on 2026-05-06 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_dispatchform_event_location_dispatchform_event_name'),
        ('returns', '0004_alter_rentalreturnitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalreturn',
            name='dispatch_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_returns', to='orders.dispatchform'),
        ),
        migrations.AlterField(
            model_name='rentalreturn',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_returns', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='rentalreturn',
            index=models.Index(fields=['dispatch_form'], name='rental_retu_dispatc_7cfecc_idx'),
        ),
    ]
