# Generated by Django 6.0.2 on 2026-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days for rental (if applicable)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='pricing_type',
            field=models.CharField(choices=[('PER_DAY', 'Per Day'), ('PER_EVENT', 'Per Event'), ('FIXED', 'Fixed Price')], default='PER_DAY', help_text='Pricing model for this item', max_length=20),
        ),
    ]
