# Generated by Django 6.0.2 on 2026-05-01 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_withdrawal_by'),
        ('labors', '0007_alter_labor_cnic'),
        ('vendors', '0005_vendor_address_vendor_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transport_vendor',
            field=models.ForeignKey(blank=True, help_text='Driver / Transport vendor (only for Transport category)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_expenses', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number (e.g. ABC-123)', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['transport_vendor'], name='expense_transpo_334c5c_idx'),
        ),
    ]
