# Generated by Django 6.0.2 on 2026-05-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_add_transport_vendor_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the expense', null=True),
        ),
    ]
