# Generated by Django 6.0.2 on 2026-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendor_area_alter_vendor_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, help_text='Full address of the vendor', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes about the vendor', null=True),
        ),
    ]
