# Generated by Django 6.0.2 on 2026-04-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0007_orderitem_pricing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='partner_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity rented from a partner (part of total quantity)'),
        ),
    ]
